#!/usr/bin/env bash
set -euo pipefail

SDK=""
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRODUCT_ROOT="$(cd "${SELF_DIR}/.." && pwd)"
ROOTFS_LIST=""
ROOTFS_EXTRACT=""
HDMI_PREVIEW_COMPARE=""
BT_PRODUCT="${PRODUCT_ROOT}/integrations/swupdate/files/bluetooth_init"
BT_SOURCE_TARGET=""
BT_SOURCE_BACKUP=""
BT_CONFIG_PRODUCT="${PRODUCT_ROOT}/packaging/aitvbox-suite/files/bluetooth.json"
BT_CONFIG_TARGET=""
BT_CONFIG_BACKUP=""
BT_HOOK_PRODUCT="${PRODUCT_ROOT}/packaging/aitvbox-suite/files/bt_init.sh"
BT_HOOK_TARGET=""
BT_HOOK_BACKUP=""
# shellcheck source=scripts/lib.sh
source "${SELF_DIR}/lib.sh"

usage() {
    echo "usage: $0 <sdk-root>" >&2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        *)
            if [[ -n "${SDK}" ]]; then
                usage
                exit 2
            fi
            SDK="$1"
            shift
            ;;
    esac
done

if [[ -z "${SDK}" ]]; then
    usage
    exit 2
fi

if [[ ! -d "${SDK}/.repo" ]]; then
    die "not a Tina SDK root: ${SDK}" "SDK 路径错或缺 .repo"
fi

# 前置输入检查
require_file "${SDK}/build/envsetup.sh" "SDK 未初始化：${SDK}"
require_file "${SDK}/build.sh" "SDK 缺 build.sh：${SDK}"
require_cmd unsquashfs "apt install squashfs-tools"
require_cmd debugfs "apt install e2fsprogs"
require_cmd blkid "apt install util-linux"
require_cmd sha256sum "apt install coreutils"

restore_sdk_pure_mode() {
    local status=$?
    if [[ -n "${ROOTFS_LIST}" && -f "${ROOTFS_LIST}" ]]; then
        rm -f "${ROOTFS_LIST}"
    fi
    if [[ -n "${ROOTFS_EXTRACT}" &&
          "${ROOTFS_EXTRACT}" == /tmp/aitvbox-rootfs-extract.* &&
          -d "${ROOTFS_EXTRACT}" ]]; then
        rm -rf -- "${ROOTFS_EXTRACT}"
    fi
    if [[ -n "${HDMI_PREVIEW_COMPARE}" &&
          "${HDMI_PREVIEW_COMPARE}" == /tmp/aitvbox-hdmi-preview.* &&
          -f "${HDMI_PREVIEW_COMPARE}" ]]; then
        rm -f "${HDMI_PREVIEW_COMPARE}"
    fi
    if [[ -n "${BT_SOURCE_BACKUP}" && -f "${BT_SOURCE_BACKUP}" &&
          -n "${BT_SOURCE_TARGET}" ]]; then
        cp -a "${BT_SOURCE_BACKUP}" "${BT_SOURCE_TARGET}"
        rm -f "${BT_SOURCE_BACKUP}"
        echo "Bluetooth source restored: ${BT_SOURCE_TARGET#${SDK}/}"
    fi
    if [[ -n "${BT_CONFIG_BACKUP}" && -f "${BT_CONFIG_BACKUP}" &&
          -n "${BT_CONFIG_TARGET}" ]]; then
        cp -a "${BT_CONFIG_BACKUP}" "${BT_CONFIG_TARGET}"
        rm -f "${BT_CONFIG_BACKUP}"
        echo "Bluetooth source restored: ${BT_CONFIG_TARGET#${SDK}/}"
    fi
    if [[ -n "${BT_HOOK_BACKUP}" && -f "${BT_HOOK_BACKUP}" &&
          -n "${BT_HOOK_TARGET}" ]]; then
        cp -a "${BT_HOOK_BACKUP}" "${BT_HOOK_TARGET}"
        rm -f "${BT_HOOK_BACKUP}"
        echo "Bluetooth source restored: ${BT_HOOK_TARGET#${SDK}/}"
    fi
    echo
    echo "Restoring SDK pure mode..."
    "${SELF_DIR}/inject_platform_kernel_config.sh" revert "${SDK}" || true
    "${SELF_DIR}/inject_sdk_files.sh" revert "${SDK}" || true
    "${SELF_DIR}/toggle_ota.sh" off "${SDK}" || true
    "${SELF_DIR}/toggle_product.sh" off "${SDK}" || true
    "${SELF_DIR}/clean_sdk_product_artifacts.sh" "${SDK}" || true
    exit "${status}"
}
trap restore_sdk_pure_mode EXIT

echo "Preparing SDK product mode..."
"${SELF_DIR}/clean_sdk_product_artifacts.sh" "${SDK}"
"${SELF_DIR}/inject_platform_kernel_config.sh" apply "${SDK}"

# 同步全部 AITVBox 薄包到 SDK。sync_to_sdk.sh 是手动步骤，产品仓库 Makefile
# 改动后若忘记同步，SDK 会用旧定义打包并静默产出过期内容，因此构建入口始终强制覆盖。
# clean_sdk_product_artifacts 不删除 SDK 的包定义；纯 SDK 语义由四个包开关共同决定，
# 由 toggle_product.sh 管理，trap 无需恢复包定义。
sync_product_packages "${PRODUCT_ROOT}" "${SDK}"

"${SELF_DIR}/toggle_product.sh" on "${SDK}"
# A/B OTA 运行时 + 地基：开 swupdate/uboot-envtools 包，注入 A/B 分区表/env/
# U-Boot bootcount（trap 里 revert/toggle off 还原 SDK 原件）。
# 仅在启用 OTA 时进行；默认关闭以保持"裸跑 SDK 即纯 SDK"。
if [[ "${AITVBOX_OTA:-0}" == "1" ]]; then
    "${SELF_DIR}/toggle_ota.sh" on "${SDK}"
    "${SELF_DIR}/inject_sdk_files.sh" apply "${SDK}"
fi

# These Bluetooth files belong to base-files rather than an AITVBox package.
# Inject the product copies into the real package source before the full build
# and keep private backups for the EXIT trap. Post-build cache edits are too
# late because rootfs.img has already been generated by then.
BT_SOURCE_TARGET="${SDK}/openwrt/target/a133/a133-b6/base-files/etc/init.d/bluetooth_init"
BT_CONFIG_TARGET="${SDK}/openwrt/target/a133/a133-b6/base-files/etc/bluetooth/bluetooth.json"
BT_HOOK_TARGET="${SDK}/openwrt/target/a133/a133-b6/base-files/etc/bluetooth/bt_init.sh"
require_file "${BT_PRODUCT}" "missing product bluetooth initializer"
require_file "${BT_SOURCE_TARGET}" "missing SDK bluetooth initializer source"
require_file "${BT_CONFIG_PRODUCT}" "missing product bluetooth config"
require_file "${BT_CONFIG_TARGET}" "missing SDK bluetooth config source"
require_file "${BT_HOOK_PRODUCT}" "missing product btmanager init hook"
require_file "${BT_HOOK_TARGET}" "missing SDK btmanager init hook source"
BT_SOURCE_BACKUP="$(mktemp /tmp/aitvbox-bluetooth-init.XXXXXX)"
BT_CONFIG_BACKUP="$(mktemp /tmp/aitvbox-bluetooth-config.XXXXXX)"
BT_HOOK_BACKUP="$(mktemp /tmp/aitvbox-bt-init-hook.XXXXXX)"
cp -a "${BT_SOURCE_TARGET}" "${BT_SOURCE_BACKUP}"
cp -a "${BT_CONFIG_TARGET}" "${BT_CONFIG_BACKUP}"
cp -a "${BT_HOOK_TARGET}" "${BT_HOOK_BACKUP}"
install -m 0755 "${BT_PRODUCT}" "${BT_SOURCE_TARGET}"
install -m 0644 "${BT_CONFIG_PRODUCT}" "${BT_CONFIG_TARGET}"
install -m 0755 "${BT_HOOK_PRODUCT}" "${BT_HOOK_TARGET}"
echo "Bluetooth source injected: ${BT_SOURCE_TARGET#${SDK}/}"
echo "Bluetooth source injected: ${BT_CONFIG_TARGET#${SDK}/}"
echo "Bluetooth source injected: ${BT_HOOK_TARGET#${SDK}/}"

# 产品仓库根注入给 aitvbox-suite 包，使其 install 阶段从 build/ + vendor/ 读产物。
# 包 Makefile 未设置此变量时会 $(error)，确保不会拷空路径。
export AITVBOX_PRODUCT_BUILD="${AITVBOX_PRODUCT_BUILD:-${PRODUCT_ROOT}}"
echo "AITVBOX_PRODUCT_BUILD=${AITVBOX_PRODUCT_BUILD}"

# 校验产物就位（避免打包阶段才发现缺失）
for f in \
    "${AITVBOX_PRODUCT_BUILD}/build/lv_port_linux/lv_backend" \
    "${AITVBOX_PRODUCT_BUILD}/build/lv_port_linux/lvglsim" \
    "${AITVBOX_PRODUCT_BUILD}/build/hdmi_preview/hdmi_preview" \
    "${AITVBOX_PRODUCT_BUILD}/build/platform/aitvbox-mcpd" \
    "${AITVBOX_PRODUCT_BUILD}/build/platform/aitvbox-agentd" \
    "${AITVBOX_PRODUCT_BUILD}/build/platform/aitvbox-controld" \
    "${AITVBOX_PRODUCT_BUILD}/build/platform/aitvbox-appd" \
    "${AITVBOX_PRODUCT_BUILD}/build/platform/aitvbox-app-policy" \
    "${AITVBOX_PRODUCT_BUILD}/build/ipkvm/aitvbox-ipkvmd" \
    "${AITVBOX_PRODUCT_BUILD}/build/ipkvm/aitvbox-kvm-video" \
    "${AITVBOX_PRODUCT_BUILD}/build/tuyaopen/your_chat_bot_QIO_1.0.1.bin" \
    "${AITVBOX_PRODUCT_BUILD}/build/aitvbox-version" \
    "${AITVBOX_PRODUCT_BUILD}/build/aitvbox-tuya-pid"; do
    if [[ ! -f "$f" ]]; then
        die "missing product artifact: $f" "run: ./scripts/build_apps.sh ${SDK}"
    fi
done

cd "${SDK}"
# SDK 自带脚本（envsetup/quick.sh、build.sh）非 set -u/-e 安全：quick.sh 用未加引号
# 的 $1、build.sh 内部有良性非零返回。source envsetup 与调用 build.sh 期间临时关闭
# nounset/errexit，靠下方显式 || die 检测真实失败。
set +eu
source build/envsetup.sh
echo "Building Tina kernel only; verified Boot0/U-Boot are intentionally untouched."
./build.sh kernel \
    || die "Tina kernel 编译失败" \
           "查看 SDK 编译日志：${SDK}/out/a133/b6/" \
           "SDK 会由 trap 自动恢复纯态"

echo "Building OpenWrt rootfs only."
./build.sh openwrt_rootfs \
    || die "Tina rootfs 编译失败" \
           "查看 SDK 编译日志：${SDK}/out/a133/b6/openwrt/" \
           "SDK 会由 trap 自动恢复纯态"

# The vendor kernel build reuses kernel/linux-4.9/.config and does not reload a
# newer board defconfig. Refuse to package an image unless the actual generated
# config contains every platform isolation and USB HID prerequisite.
KERNEL_OUTPUT_CONFIG="${SDK}/kernel/linux-4.9/output/.config"
require_file "${KERNEL_OUTPUT_CONFIG}" "Tina kernel did not generate output/.config"
for option in \
    CONFIG_HIDRAW \
    CONFIG_INPUT_UINPUT \
    CONFIG_USB_CONFIGFS_F_HID \
    CONFIG_SECCOMP \
    CONFIG_SECCOMP_FILTER; do
    if ! grep -qx "${option}=y" "${KERNEL_OUTPUT_CONFIG}"; then
        die "product kernel requirement missing: ${option}=y" \
            "generated config: ${KERNEL_OUTPUT_CONFIG}" \
            "firmware packaging aborted"
    fi
done
echo "Kernel platform requirements verified: HID + SECCOMP filter"

./build.sh pack \
    || die "Tina SDK pack 失败" \
           "查看 pack 日志：${SDK}/out/a133/b6/pack_out" \
           "SDK 会由 trap 自动恢复纯态"
set -eu

ROOTFS_IMAGE="${SDK}/out/a133/b6/openwrt/rootfs.img"
FIRMWARE_IMAGE="${SDK}/out/a133/b6/openwrt/a133_linux_b6_uart0.img"
require_file "${ROOTFS_IMAGE}" "Tina pack 未生成 rootfs.img"
require_file "${FIRMWARE_IMAGE}" "Tina pack 未生成最终固件镜像"
if [[ ! -s "${ROOTFS_IMAGE}" || ! -s "${FIRMWARE_IMAGE}" ]]; then
    die "Tina pack generated an empty image"
fi

# Pack success alone does not prove that OpenWrt installed the product packages.
# Tina products may use either SquashFS or a fixed-size ext4 rootfs. Inspect the
# filesystem that was actually packed and fail before publishing an incomplete
# image.
ROOTFS_TYPE="$(blkid -p -s TYPE -o value "${ROOTFS_IMAGE}" 2>/dev/null || true)"
case "${ROOTFS_TYPE}" in
    squashfs)
        ROOTFS_LIST="$(mktemp /tmp/aitvbox-rootfs-list.XXXXXX)"
        unsquashfs -lln "${ROOTFS_IMAGE}" >"${ROOTFS_LIST}" \
            || die "无法读取最终 rootfs SquashFS"
        ;;
    ext2|ext3|ext4)
        ROOTFS_EXTRACT="$(mktemp -d /tmp/aitvbox-rootfs-extract.XXXXXX)"
        debugfs -R "rdump / ${ROOTFS_EXTRACT}" "${ROOTFS_IMAGE}" \
            >/dev/null 2>&1 ||
            die "无法读取最终 ${ROOTFS_TYPE} rootfs"
        ;;
    *)
        die "unsupported final rootfs filesystem: ${ROOTFS_TYPE:-unknown}"
        ;;
esac

for path in \
    /usr/bin/lvglsim \
    /usr/bin/lv_backend \
    /usr/bin/hdmi_preview \
    /usr/bin/aitvbox-mcpd \
    /usr/bin/aitvbox-agentd \
    /usr/bin/aitvbox-controld \
    /usr/bin/aitvbox-appd \
    /usr/bin/aitvbox-app-policy \
    /usr/bin/aitvbox-appctl \
    /usr/bin/aitvbox-hidctl \
    /usr/bin/aitvbox-ipkvmd \
    /usr/bin/aitvbox-kvm-video \
    /etc/init.d/aitvbox \
    /etc/init.d/aitvbox-control \
    /etc/init.d/aitvbox-apps \
    /etc/init.d/aitvbox-usb-hid \
    /etc/init.d/aitvbox-ipkvm \
    /etc/init.d/bluetooth_init; do
    if [[ "${ROOTFS_TYPE}" == squashfs ]]; then
        if ! awk -v expected="squashfs-root${path}" \
            '$1 == "-rwxr-xr-x" && $2 == "0/0" && $NF == expected { found = 1 }
             END { exit !found }' "${ROOTFS_LIST}"; then
            die "final rootfs missing root-owned executable: ${path}"
        fi
    else
        ROOTFS_STAT="$(
            debugfs -R "stat ${path}" "${ROOTFS_IMAGE}" 2>/dev/null || true
        )"
        if ! grep -Eq 'Type:[[:space:]]+regular.*Mode:[[:space:]]+0755' \
            <<<"${ROOTFS_STAT}" ||
            ! grep -Eq 'User:[[:space:]]+0[[:space:]]+Group:[[:space:]]+0' \
                <<<"${ROOTFS_STAT}"; then
            die "final rootfs missing root-owned executable: ${path}"
        fi
    fi
done

# Matching paths and modes are insufficient: stale SDK copies can look valid.
# Compare all base-files Bluetooth injections byte-for-byte with product sources.
for bluetooth_spec in \
    "etc/init.d/bluetooth_init:${BT_PRODUCT}" \
    "etc/bluetooth/bluetooth.json:${BT_CONFIG_PRODUCT}" \
    "etc/bluetooth/bt_init.sh:${BT_HOOK_PRODUCT}"; do
    bluetooth_path="${bluetooth_spec%%:*}"
    bluetooth_product="${bluetooth_spec#*:}"
    if [[ "${ROOTFS_TYPE}" == squashfs ]]; then
        if ! unsquashfs -cat "${ROOTFS_IMAGE}" "${bluetooth_path}" 2>/dev/null \
            | cmp -s - "${bluetooth_product}"; then
            die "final rootfs contains stale Bluetooth source: /${bluetooth_path}"
        fi
    elif ! cmp -s "${ROOTFS_EXTRACT}/${bluetooth_path}" \
        "${bluetooth_product}"; then
        die "final rootfs contains stale Bluetooth source: /${bluetooth_path}"
    fi
done

# The package installs an out-of-tree product binary. Comparing only its mode
# and pathname allows stale OpenWrt package caches to silently survive a new
# product build. OpenWrt strips executables during package installation, so
# compare against a copy processed by the same target strip tool.
HDMI_PREVIEW_PRODUCT="${AITVBOX_PRODUCT_BUILD}/build/hdmi_preview/hdmi_preview"
HDMI_PREVIEW_STRIP="${SDK}/prebuilt/rootfsbuilt/aarch64/toolchain-sunxi-glibc-gcc-1130/toolchain/bin/aarch64-openwrt-linux-strip"
require_file "${HDMI_PREVIEW_STRIP}" "missing A133 target strip tool"
HDMI_PREVIEW_COMPARE="$(mktemp /tmp/aitvbox-hdmi-preview.XXXXXX)"
cp "${HDMI_PREVIEW_PRODUCT}" "${HDMI_PREVIEW_COMPARE}"
"${HDMI_PREVIEW_STRIP}" "${HDMI_PREVIEW_COMPARE}"
if [[ "${ROOTFS_TYPE}" == squashfs ]]; then
    if ! unsquashfs -cat "${ROOTFS_IMAGE}" usr/bin/hdmi_preview 2>/dev/null \
        | cmp -s - "${HDMI_PREVIEW_COMPARE}"; then
        die "final rootfs contains a stale hdmi_preview"
    fi
elif ! cmp -s "${ROOTFS_EXTRACT}/usr/bin/hdmi_preview" \
    "${HDMI_PREVIEW_COMPARE}"; then
    die "final rootfs contains a stale hdmi_preview"
fi
rm -f "${HDMI_PREVIEW_COMPARE}"
HDMI_PREVIEW_COMPARE=""

if [[ "${AITVBOX_AUDIO_DIAGNOSTIC:-0}" == "1" ]]; then
	for diagnostic_path in \
		/etc/init.d/aitvbox-audio-diagnostic \
		/etc/audio-chain-test.wav \
		/etc/rc.d/S99aitvbox-audio-diagnostic; do
        if [[ "${ROOTFS_TYPE}" == squashfs ]]; then
            if ! awk -v expected="squashfs-root${diagnostic_path}" \
                '$NF == expected { found = 1 } END { exit !found }' \
                "${ROOTFS_LIST}"; then
                die "diagnostic rootfs missing: ${diagnostic_path}"
            fi
        elif [[ ! -e "${ROOTFS_EXTRACT}${diagnostic_path}" ]]; then
            die "diagnostic rootfs missing: ${diagnostic_path}"
        fi
    done
fi

if [[ "${ROOTFS_TYPE}" == squashfs ]]; then
    if grep -Eq 'squashfs-root/.*/(100ask_ecdsa\.pem|tls\.key|id_rsa)$' \
        "${ROOTFS_LIST}"; then
        die "private key file detected in final rootfs"
    fi
elif find "${ROOTFS_EXTRACT}" -type f \
    \( -name 100ask_ecdsa.pem -o -name tls.key -o -name id_rsa \) \
    -print -quit | grep -q .; then
    die "private key file detected in final rootfs"
fi

[[ -z "${ROOTFS_LIST}" ]] || rm -f "${ROOTFS_LIST}"
ROOTFS_LIST=""
if [[ -n "${ROOTFS_EXTRACT}" ]]; then
    rm -rf -- "${ROOTFS_EXTRACT}"
    ROOTFS_EXTRACT=""
fi

echo "Final ${ROOTFS_TYPE} rootfs verified: product services are root-owned executable files"
echo "Firmware SHA256: $(sha256sum "${FIRMWARE_IMAGE}" | awk '{print $1}')"
echo "Firmware build complete: ${FIRMWARE_IMAGE}"
